'use strict';
(()=>{
const KEY='noon100k-cold-v2',SCHEMA='noon100k-cold-v2',MAX=100000000,OWN={wei:'阿衛',wife:'太太',both:'共同'},REL={cold:'完全陌生',unknown:'待核對',customer:'原客戶／舊案',friend:'親友／熟人',referral:'熟人介紹',follower:'既有粉絲'};
const PHASES=[
['09:00–09:10','先定義實驗，不先找熟客',[
['wei','09:00–09:04','鎖定一個陌生客群','預設宜蘭室內設計／裝修；檢查週日上午是否可合理聯繫。只選一類，不同時賣五種服務。','客群及篩選規則'],
['wife','09:00–09:04','確認一個商品與供給','向外包核對範圍、成本、開工日和產能。拿不到確認就只訪談，不收款承諾做不到的事。','39,800 方案與產能依據'],
['both','09:04–09:07','確認零起點與排除規則','名單、預約、收款全部從 0；不准熟客、在談案、既有粉絲或熟人轉介。工具與真實作品可以用。','共同認可的實驗邊界'],
['both','09:07–09:10','寫好書面範圍及同一套開場','正確承攬主體、含稅口徑、交期、驗收、付款與取消約定。非總部官方方案；不說保證增加營收。','一份一致的試賣報價']]],
['09:10–09:25','從公開商務來源建第一批名單',[
['wei','09:10–09:20','查找第一批 8–10 家陌生公司','人工查看公開商家頁及官網，記錄網址、查得時間與一項可見現象。看不到表單不等於公司必有痛點。','8–10 個待核對名單，目標非保證'],
['wife','09:10–09:20','整理一個共用接單流程示範','用自有或獲授權素材示範「服務介紹→需求表→真人報價→追蹤」。標示示範，不編造客戶與成效。','一份能在兩分鐘看懂的示範'],
['wei','09:20–09:25','核對陌生關係、來源與重複','公司是獨立採購單位；同公司不同分店或不同電話不要灌成不同客戶。無法確認就標待核對。','可計入與排除名單分開'],
['wife','09:20–09:25','補查 3–5 家並分配聯絡人','只用公開商務窗口；看營業與聯絡方式。夫妻不要同時聯絡同一公司。','夫妻不重複的第一輪名單']]],
['09:25–10:00','第一輪陌生接觸：先確認是否有問題',[
['wei','09:25–09:45','人工聯絡第一批決策者','說明真實身分及公開來源，先問可否談一分鐘。沒接通只算嘗試；拒絕就停止。','實際首聯時間與結果'],
['wife','09:25–09:45','平行聯絡自己的陌生名單','使用同一客群、商品與價位；不找婚禮熟人補收款。取得同意再送示範，不群發相同訊息。','獨立、不重複的接觸紀錄'],
['wei','09:45–09:55','與有意願的決策者談具體流程','問最近一次詢問如何處理、卡在哪、誰決定、是否有預算與採購時間。需要的是流量就坦承本案不適合。','需求事實，不是禮貌性稱讚'],
['wife','09:45–09:55','持續首聯或補齊有效來源','有回覆才排十到十五分鐘短談。未回覆者標待回覆；不冒充已與老闆聯繫。','可約談對象／未接通原因'],
['both','09:55–10:00','更新第一輪漏斗','只列實際數字。接不通先查時段與管道；能談卻沒需求就記錄不匹配，不立刻判斷市場不存在。','第一輪樣本與卡點']]],
['10:00–10:40','把陌生需求變成具體提案',[
['wei','10:00–10:15','第一場經同意的需求示範','只對有具體問題的人展示共用示範；說清 39,800 元買到什麼、不能保證什麼。','真實需求／採購條件'],
['wife','10:00–10:15','依對方問題補一頁對應說明','只改必要文字與流程，不免費做完整客製網站。無已同意約談者就繼續人工開發。','一頁提案，不開新產品'],
['wei','10:15–10:30','第二場短談或繼續首聯','沒有約談就做開發，不憑空填行程。需求與決策方式確認後，才勾合格需求。','第二個真實結果'],
['wife','10:15–10:30','獨立完成另一場短談或聯繫','有需求再發完整報價；不只傳價目表就當客戶接受。使用真實作品建立信任。','明確報價或排除原因'],
['both','10:30–10:40','依證據調整一項開場並記版次','若有共通誤解只改說法，記錄修改時間。不同時換客群、價格與服務，避免不知道哪一項有效。','版本紀錄／逐案下一步']]],
['10:40–11:15','正式報價：讓陌生人自己決定',[
['wei','10:40–10:55','將約定範圍送到真正決策者','把總價、首款、開工、驗收、成本另列項與取消方式寫清楚。只跟有需求者談，不用衝十萬當理由。','可核對的報價與送出時間'],
['wife','10:40–10:55','核對每份承諾及可交付量','每接一案重新看外包與夫妻排程，不超接。不降低品質，也不保證自動成交或營業額。','交付容量與費用邊界'],
['wei','10:55–11:10','處理價格、信任與交期疑問','真實補資料，不編假案例、不宣稱最後名額。對方需要時間就約後續；沒有書面決定不算合作。','書面決定／未決原因'],
['wife','10:55–11:15','處理自己的報價及資料登錄','同規則記來源、需求、報價、書面確認；只收與約定相符的款項。記錄不同拒絕原因供驗證。','不灌水的合作紀錄']]],
['11:15–11:40','核對付款與後續交付，不催出假成果',[
['wei','11:15–11:25','只回訪已約定回覆的陌生客','對方拒絕就停止，未約回覆不連環催。確認範圍與開工，不為時限交換不合理讓步。','最後一輪真實答覆'],
['wife','11:15–11:25','核對真實入帳並連結來源','首款、已交付收入、排除款分開填。自行查實帳戶入帳，不拿匯款意向當現金。','憑證代號與款項性質'],
['wei','11:25–11:40','完成書面交接及履約排程','新案若只是未來交付，列為訂金責任，不在上午虛構驗收；確有新交付才記實際時間。','客戶同意的開工與驗收安排'],
['wife','11:25–11:40','逐筆核對成本及不重複計數','外包、工時、材料、交通及稅費依一致口徑列；同一憑證只登一筆，未成交成本也算。','真實成本與待付義務']]],
['11:40–11:59','以陌生樣本與真實收益結算',[
['wei','11:40–11:48','查核漏斗與來源排除','每家公司查得及首次聯繫都在本輪；排除熟客、既有粉絲、熟人介紹及不明來源。截止後結果另記。','最終有效樣本與付款人數'],
['wife','11:40–11:48','完成共同成本與入帳核對','新交付收入須在本輪驗收及實收；預收不變成淨利，成本未查清就不顯示達標。','現金、訂金、淨收益分開'],
['both','11:48–11:52','整理後續聯絡同意與履約責任','已成交者確認排程；尚未成交只保留對方同意的下一步。拒絕者不繼續聯繫，也不把下週付款算成上午成果。','交付清單與同意回訪時間'],
['both','11:52–11:59','匯出結果，寫下下一輪只改什麼','無付款不假裝成功，也不以小樣本斷言市場不存在。有付款仍要驗證交付、利潤與重複獲客；正常履行後續承諾。','備份、實驗結論與後續責任']]]
];
let taskNum=0;PHASES.forEach((p,pi)=>p[2].forEach(t=>{t.id='c'+(++taskNum);t.phase=pi}));const TASKS=PHASES.flatMap(p=>p[2]);
const $=s=>document.getElementById(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=x=>{const n=Number(x);if(!Number.isSafeInteger(n)||n<0||n>MAX)throw Error('金額須為 0 到一億元的整數');return n},money=x=>(x<0?'−$':'$')+Math.round(Math.abs(x||0)).toLocaleString('en-US'),norm=x=>String(x||'').normalize('NFKC').toLowerCase().replace(/\s+/g,''),uid=()=>globalThis.crypto?.randomUUID?.()||'c'+Date.now().toString(36)+Math.random().toString(36).slice(2),nowLocal=()=>new Date(Date.now()+28800000).toISOString().slice(0,19);
function dateOK(d){return /^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T00:00:00Z'))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d}
function time(s){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?$/.test(s||'')||!dateOK(s.slice(0,10))||+s.slice(11,13)>23||+s.slice(14,16)>59||+(s.slice(17,19)||0)>59)return NaN;return Date.parse(s+'+08:00')}
function inWindow(s,d,now=Date.now()){const t=time(s);return Number.isFinite(t)&&t>=time(d+'T09:00:00')&&t<time(d+'T12:00:00')&&t<=now}
function publicURL(s){try{const u=new URL(s);return /^https?:$/.test(u.protocol)&&!u.username&&!u.password}catch{return false}}
function blank(d='2026-09-27'){return {schema:SCHEMA,version:2,date:d,days:{},updatedAt:0}}
function blankDay(){return {cohort:'宜蘭室內設計／裝修公司；逐家確認週日上午可聯繫',ready:{},tasks:{},leads:[],receipts:[],sharedCost:0,sharedChecked:false,learning:''}}
let state=blank(),canStore=true;
function validate(s){
 if(!s||s.schema!==SCHEMA||s.version!==2||!dateOK(s.date)||!s.days||typeof s.days!=='object'||Array.isArray(s.days)||Object.keys(s.days).length>366)throw Error('只支援陌生開發 V2 備份；不匯入 V1 熟客資料');
 const out=blank(s.date);out.updatedAt=Number(s.updatedAt)||0;
 for(const [dt,v]of Object.entries(s.days)){
  if(!dateOK(dt)||!v||!Array.isArray(v.leads)||!Array.isArray(v.receipts)||v.leads.length>1000||v.receipts.length>2000)throw Error('備份資料格式或筆數不正確');
  const d=blankDay();d.cohort=String(v.cohort||'').slice(0,100);d.learning=String(v.learning||'').slice(0,4000);d.sharedCost=num(v.sharedCost||0);d.sharedChecked=v.sharedChecked===true;for(const k of ['scope','supply','demo'])d.ready[k]=v.ready?.[k]===true;
  for(const t of TASKS){const q=v.tasks?.[t.id];if(q)d.tasks[t.id]={done:q.done===true,note:String(q.note||'').slice(0,1500)}}
  const ids=new Set(),names=new Set();
  for(const l of v.leads){if(!l||typeof l.id!=='string'||!l.id||ids.has(l.id)||!String(l.name||'').trim()||names.has(norm(l.name)))throw Error('名單有重複公司／識別碼');ids.add(l.id);names.add(norm(l.name));
   const n={};for(const k of ['id','name','owner','relation','channel','url','foundAt','touchAt','decisionAt','quoteAt','signedAt','next'])n[k]=String(l[k]||'').slice(0,k==='next'?1500:k==='url'?1000:100);
   if(!OWN[n.owner]||!REL[n.relation]||!publicURL(n.url))throw Error('名單的分工、關係或網址不正確');n.amount=num(l.amount);for(const k of ['need','declined','verified'])n[k]=l[k]===true;checkLead(n);d.leads.push(n);
  }
  const rids=new Set(),refs=new Set();for(const r of v.receipts){if(!r||typeof r.id!=='string'||rids.has(r.id)||!ids.has(r.leadId)||!r.ref||refs.has(norm(r.ref)))throw Error('款項識別、對應名單或憑證重複／遺失');rids.add(r.id);refs.add(norm(r.ref));const n={};for(const k of ['id','leadId','kind','ref','paidAt','acceptedAt','proof'])n[k]=String(r[k]||'').slice(0,k==='proof'?1500:100);for(const k of ['cash','revenue','cost'])n[k]=num(r[k]);for(const k of ['verified','accepted','costChecked'])n[k]=r[k]===true;checkReceipt(n,d.receipts,d.leads);d.receipts.push(n)}out.days[dt]=d;
 }return out;
}
function checkLead(l){let previous=-Infinity;for(const k of ['foundAt','touchAt','decisionAt','quoteAt','signedAt']){if(l[k]){const t=time(l[k]);if(!Number.isFinite(t)||t<previous)throw Error('名單時間須依查得、首聯、決策對話、報價、合作順序填寫');previous=t}}
 if(!l.foundAt)throw Error('請填實際查得名單時間');if(l.decisionAt&&!l.touchAt||l.quoteAt&&(!l.decisionAt||!l.need)||l.signedAt&&!l.quoteAt||l.need&&!l.decisionAt)throw Error('先記實際聯繫、決策者對話與需求，再記報價／合作；沒有發生就留空');if(l.signedAt&&!l.amount)throw Error('合作總額不可為 0');
}
function checkReceipt(r,others,leads){const l=leads.find(l=>l.id===r.leadId);if(!l)throw Error('請先建立對應名單');if(!['deposit','earned','excluded'].includes(r.kind))throw Error('款項性質不正確');if(!r.ref.trim())throw Error('請填不重複憑證代號');if(others.some(x=>x.id!==r.id&&norm(x.ref)===norm(r.ref)))throw Error('這個憑證代號已使用，不可重複計入');for(const k of ['paidAt','acceptedAt'])if(r[k]&&!Number.isFinite(time(r[k])))throw Error('付款／驗收時間不正確');if(r.kind!=='earned'&&(r.revenue>0||r.accepted))throw Error('預收／舊款不能填新交付收入或勾新驗收');const prior=others.filter(x=>x.id!==r.id&&x.leadId===r.leadId);if(prior.reduce((a,x)=>a+x.cash,0)+r.cash>l.amount||prior.reduce((a,x)=>a+x.revenue,0)+r.revenue>l.amount)throw Error('同一案累計入帳或交付收入超過合約，請去重或先核對合約金額');}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw))}catch(e){canStore=false;setTimeout(()=>toast('本機資料讀取失敗，未覆蓋舊資料：'+e.message),100)}
function day(){return state.days[state.date]||(state.days[state.date]=blankDay())}
function save(){state.updatedAt=Date.now();if(canStore)try{localStorage.setItem(KEY,JSON.stringify(state));$('storageStatus').textContent='已自動儲存於此瀏覽器 · 不跨裝置同步'}catch{canStore=false}$('storageStatus').textContent=canStore?'已自動儲存於此瀏覽器 · 不跨裝置同步':'無法持久儲存，關閉前務必匯出備份';}
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500)}
function sourceReason(l,d=state.date,now=Date.now()){if(l.relation!=='cold')return '排除：'+(REL[l.relation]||'來源不明');if(!l.verified)return '待查核陌生來源';if(!publicURL(l.url))return '缺可核對公開來源';if(!inWindow(l.foundAt,d,now))return '查得名單不在本輪時段';return ''}
function contactOK(l,d=state.date,now=Date.now()){return !sourceReason(l,d,now)&&inWindow(l.touchAt,d,now)&&time(l.touchAt)>=time(l.foundAt)}
function signOK(l,d=state.date,now=Date.now()){return contactOK(l,d,now)&&inWindow(l.decisionAt,d,now)&&l.need&&inWindow(l.quoteAt,d,now)&&inWindow(l.signedAt,d,now)&&time(l.signedAt)>=time(l.quoteAt)}
function calc(d=day(),dt=state.date,now=Date.now()){
 const sourced=d.leads.filter(l=>!sourceReason(l,dt,now)),contact=d.leads.filter(l=>contactOK(l,dt,now)),decision=contact.filter(l=>inWindow(l.decisionAt,dt,now)),qualified=decision.filter(l=>l.need),quoted=qualified.filter(l=>inWindow(l.quoteAt,dt,now));
 const rows=d.receipts.map(r=>{const l=d.leads.find(l=>l.id===r.leadId);let reason=!l?'沒有對應名單':sourceReason(l,dt,now);if(!reason&&!contactOK(l,dt,now))reason='首次接觸不在本輪時段';if(!reason&&r.kind==='excluded')reason='舊款／其他排除';if(!reason&&!signOK(l,dt,now))reason='缺本輪書面合作條件';if(!reason&&(!r.verified||!r.proof.trim()||!inWindow(r.paidAt,dt,now)||time(r.paidAt)<time(l.signedAt)))reason='入帳時間／憑證待核對';const cashOK=!reason;let grossOK=cashOK;if(grossOK&&r.kind!=='earned'){grossOK=false;reason='預收款：非已賺收入'}if(grossOK&&(!r.accepted||!inWindow(r.acceptedAt,dt,now)||time(r.acceptedAt)<time(l.signedAt))){grossOK=false;reason='未完成本輪新交付驗收'}if(grossOK&&!r.costChecked){grossOK=false;reason='全部成本待核對'}if(grossOK&&(!r.cash||!r.revenue)){grossOK=false;reason='沒有新交付實收收入'}const gross=grossOK?Math.min(r.cash,r.revenue):0;return {r,l,cash:cashOK?r.cash:0,gross,net:gross-r.cost,reason:grossOK?'依輸入條件可計收入':reason,eligible:grossOK}});
 const paid=new Set(rows.filter(x=>x.cash>0).map(x=>x.r.leadId)),cash=rows.reduce((a,x)=>a+x.cash,0),gross=rows.reduce((a,x)=>a+x.gross,0),cost=rows.reduce((a,x)=>a+x.r.cost,0)+d.sharedCost,net=gross-cost,checked=d.sharedChecked&&d.receipts.every(r=>r.costChecked);
 return {sourced,contact,decision,qualified,quoted,paid,rows,cash,gross,cost,net,checked,achieved:checked&&net>=100000,signed:d.leads.filter(l=>signOK(l,dt,now)).reduce((a,l)=>a+l.amount,0),deposit:rows.filter(x=>x.r.kind==='deposit').reduce((a,x)=>a+x.cash,0)};
}
function stats(){const d=day(),m=calc();$('signedTotal').textContent=money(m.signed);$('cashTotal').textContent=money(m.cash);$('netTotal').textContent=money(m.net);$('gapTotal').textContent=money(Math.max(0,100000-m.net));$('goalStatus').textContent=m.achieved?'依人工紀錄達標，仍須保存證據':m.net>=100000?'金額到線，成本查核未完成':'尚未達標，不改算法';$('costHint').textContent=m.checked?'已核對成本；所有數字仍須對照原始憑證。':'未核對全部成本前，不顯示淨收益達標。';$('funnel').innerHTML=[['來源合格',m.sourced.length],['已首次聯繫',m.contact.length],['決策者對話',m.decision.length],['需求已確認',m.qualified.length],['正式報價',m.quoted.length],['實際付款人',m.paid.size]].map(([s,n])=>`<div><strong>${n}</strong>${s}</div>`).join('');const excluded=d.leads.length-m.sourced.length;
 $('finding').textContent=m.paid.size?`有 ${m.paid.size} 位不同陌生客戶實際付款，屬初步付費證據；尚未證明可複製、交付品質或最終利潤。`:'尚未有陌生付款證據。接通、稱讚、有興趣與報價，都不等於完成付費驗證。';
 $('summaryText').textContent=`本輪名單 ${d.leads.length} 家，來源合格 ${m.sourced.length} 家，排除／待核對 ${excluded} 家；實際首次聯繫 ${m.contact.length} 家、決策者對話 ${m.decision.length} 家、確認需求 ${m.qualified.length} 家、正式報價 ${m.quoted.length} 家、付款 ${m.paid.size} 家。陌生收款 ${money(m.cash)}（其中訂金 ${money(m.deposit)}），嚴格新收入 ${money(m.gross)}，本輪全部已列成本 ${money(m.cost)}，保守淨收益 ${money(m.net)}。${m.achieved?'依輸入紀錄達到十萬元。':'未證明中午前淨賺十萬元。'}這不是自動銀行核驗或大樣本市場結論。`;
 const start=time(state.date+'T09:00:00'),end=time(state.date+'T12:00:00'),now=Date.now(),before=now<start,active=now>=start&&now<end;let sec=Math.max(0,Math.floor(((before?start:end)-now)/1000));$('clock').textContent=[Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(n=>String(n).padStart(2,'0')).join(':');$('clockNote').textContent=(before?'距離零起點開始':active?'距離中午結算':'本輪已截止，如實記錄')+' · 台灣時間';$('runStatus').textContent=before?'尚未開始':active?'陌生驗證中':'已截止';$('taskProgress').textContent=`${TASKS.filter(t=>d.tasks[t.id]?.done).length} / ${TASKS.length} 完成`;
}
function tasks(){const d=day(),who=$('ownerFilter').value,hide=$('unfinished').checked,opens=new Map([...document.querySelectorAll('.cold-phase')].map(e=>[e.dataset.p,e.open]));$('taskList').innerHTML=PHASES.map((p,i)=>{const list=p[2].filter(t=>(who==='all'||t[0]===who||t[0]==='both')&&(!hide||!d.tasks[t.id]?.done));return list.length?`<details class="cold-phase" data-p="${i}" ${opens.get(String(i))!==false?'open':''}><summary><span>${p[0]}</span><span>${esc(p[1])}</span><small>${p[2].filter(t=>d.tasks[t.id]?.done).length}/${p[2].length}</small></summary>${list.map(t=>{const q=d.tasks[t.id]||{};return `<div class="cold-task ${q.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${q.done?'checked':''} aria-label="${esc(t[2])}"><div><strong class="cold-task-title">${esc(t[2])}</strong><p>${esc(t[3])}</p><span class="cold-small">${t[1]} · ${OWN[t[0]]} · 產出：${esc(t[4])}</span><details ${q.note?'open':''}><summary>執行備註</summary><textarea data-note="${t.id}" maxlength="1500" aria-label="${esc(t[2])}備註">${esc(q.note||'')}</textarea></details></div></div>`}).join('')}</details>`:''}).join('')||'<p class="cold-empty">目前篩選沒有待辦。</p>'}
function tables(){const d=day(),m=calc();$('leadList').innerHTML=!d.leads.length?'<div class="cold-empty">從 0 開始，沒有預塞客戶。09:00 後查找第一家公開商務來源再新增。</div>':`<table class="cold-table"><thead><tr><th>公司／來源</th><th>陌生資格／進度</th><th>報價／合作</th><th>下一步／操作</th></tr></thead><tbody>${d.leads.map(l=>{const reason=sourceReason(l),stage=signOK(l)?'書面合作':l.quoteAt?'已填報價':l.need?'需求確認':l.decisionAt?'決策對話':l.touchAt?'已填首聯':'待首聯';return `<tr><td><strong>${esc(l.name)}</strong><small>${OWN[l.owner]} · <a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">公開來源</a></small><small>查得 ${esc(l.foundAt.replace('T',' '))}</small></td><td><span class="cold-badge ${reason?'warn':''}">${esc(reason||'來源合格')}</span><small>${stage}${l.declined?' · 已拒絕，禁止續聯':''}</small></td><td>${money(l.amount)}<small>不是已收／已賺</small></td><td>${esc(l.next||'尚未填具體下一步')}<div class="cold-actions"><button class="cold-link" data-edit-lead="${esc(l.id)}">編輯</button><button class="cold-link" data-pay-lead="${esc(l.id)}">記款項</button><button class="cold-link cold-danger" data-del-lead="${esc(l.id)}">刪除</button></div></td></tr>`}).join('')}</tbody></table>`;
 $('receiptList').innerHTML=!m.rows.length?'<div class="cold-empty">尚無實際款項。未收到的款項不要先填成收入。</div>':`<table class="cold-table"><thead><tr><th>公司／款項</th><th>合格陌生入帳</th><th>合格新收入</th><th>本次成本</th><th>淨貢獻／查核</th></tr></thead><tbody>${m.rows.map(x=>`<tr><td>${esc(x.l?.name||'遺失名單')}<small>${esc(x.r.ref)} · ${{deposit:'未來服務預收',earned:'新交付',excluded:'排除'}[x.r.kind]}</small><small>填列實收 ${money(x.r.cash)}</small></td><td>${money(x.cash)}</td><td>${money(x.gross)}</td><td>${money(x.r.cost)}</td><td><strong>${money(x.net)}</strong><small>${esc(x.reason)}</small><div class="cold-actions"><button class="cold-link" data-edit-receipt="${esc(x.r.id)}">編輯</button><button class="cold-link cold-danger" data-del-receipt="${esc(x.r.id)}">刪除</button></div></td></tr>`).join('')}</tbody></table>`;
}
function render(){const d=day();$('missionDate').value=state.date;$('cohort').value=d.cohort;$('sharedCost').value=d.sharedCost;$('sharedChecked').checked=d.sharedChecked;$('learning').value=d.learning;document.querySelectorAll('[data-ready]').forEach(e=>e.checked=d.ready[e.dataset.ready]===true);tasks();tables();stats()}
function fill(form,obj){form.reset();for(const [k,v]of Object.entries(obj)){const e=form.elements.namedItem(k);if(!e)continue;if(e.type==='checkbox')e.checked=v===true;else e.value=v??''}}
function leadModal(id){const l=day().leads.find(x=>x.id===id);fill($('leadForm'),l||{id:'',owner:'wei',relation:'unknown',channel:'official',amount:39800,foundAt:nowLocal()});$('leadTitle').textContent=l?'編輯來源與進度':'新增陌生名單';$('leadDialog').showModal()}
function receiptModal(id,leadId){if(!day().leads.length)return toast('先建立真實來源名單，再記實際款項');const f=$('receiptForm');f.elements.leadId.innerHTML=day().leads.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}（${REL[l.relation]}）</option>`).join('');const r=day().receipts.find(x=>x.id===id);fill(f,r||{id:'',leadId:leadId||day().leads[0].id,kind:'deposit',cash:0,revenue:0,cost:0});$('receiptTitle').textContent=r?'編輯實際款項':'記錄實際款項';$('receiptDialog').showModal()}
$('leadForm').addEventListener('submit',e=>{e.preventDefault();try{const f=e.target,l={};for(const k of ['id','name','owner','relation','channel','url','foundAt','touchAt','decisionAt','quoteAt','signedAt','next'])l[k]=f.elements[k].value.trim();l.id=l.id||uid();l.amount=num(f.elements.amount.value);for(const k of ['verified','need','declined'])l[k]=f.elements[k].checked;if(!publicURL(l.url))throw Error('請填 http(s) 公開商務網址');if(day().leads.some(x=>x.id!==l.id&&norm(x.name)===norm(l.name)))throw Error('這家公司已建立名單，請編輯原紀錄');checkLead(l);const old=day().leads.find(x=>x.id===l.id);if(old?.declined&&!l.declined&&!confirm('原紀錄已拒絕行銷。只有對方重新同意聯繫才能解除；已取得同意嗎？'))return;const cash=day().receipts.filter(r=>r.leadId===l.id).reduce((a,r)=>a+r.cash,0),revenue=day().receipts.filter(r=>r.leadId===l.id).reduce((a,r)=>a+r.revenue,0);if(Math.max(cash,revenue)>l.amount)throw Error('新合約金額小於已有款項，請先核對');const i=day().leads.findIndex(x=>x.id===l.id);if(i<0)day().leads.push(l);else day().leads[i]=l;save();$('leadDialog').close();render();toast('名單已儲存；不合格來源不計陌生成果')}catch(err){toast(err.message)}});
$('receiptForm').addEventListener('submit',e=>{e.preventDefault();try{const f=e.target,r={};for(const k of ['id','leadId','kind','ref','paidAt','acceptedAt','proof'])r[k]=f.elements[k].value.trim();r.id=r.id||uid();for(const k of ['cash','revenue','cost'])r[k]=num(f.elements[k].value);for(const k of ['verified','accepted','costChecked'])r[k]=f.elements[k].checked;checkReceipt(r,day().receipts,day().leads);const i=day().receipts.findIndex(x=>x.id===r.id);if(i<0)day().receipts.push(r);else day().receipts[i]=r;day().sharedChecked=false;save();$('receiptDialog').close();render();toast('已儲存；請重新核對共同成本。訂金不算已賺收入')}catch(err){toast(err.message)}});
$('newLead').onclick=()=>leadModal();$('newReceipt').onclick=()=>receiptModal();$('ownerFilter').onchange=tasks;$('unfinished').onchange=tasks;$('togglePhases').onclick=()=>{const all=[...document.querySelectorAll('.cold-phase')],open=all.some(e=>e.open);all.forEach(e=>e.open=!open);$('togglePhases').textContent=open?'展開時段':'收合時段'};
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.task){const q=day().tasks[el.dataset.task]||{};day().tasks[el.dataset.task]={...q,done:el.checked};save();tasks();stats()}if(el.dataset.ready){day().ready[el.dataset.ready]=el.checked;save()}});
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.note){day().tasks[el.dataset.note]={...day().tasks[el.dataset.note],note:el.value};save()}});
$('missionDate').onchange=e=>{if(!dateOK(e.target.value))return toast('請選有效執行日期');state.date=e.target.value;save();render()};$('cohort').onchange=e=>{if(day().leads.some(l=>l.touchAt)&&!confirm('已有首聯紀錄。改客群會影響實驗比較；請在實驗筆記記下時間與原因。確定修改？')){e.target.value=day().cohort;return}day().cohort=e.target.value;save()};$('learning').oninput=e=>{day().learning=e.target.value;save()};$('sharedCost').onchange=e=>{try{day().sharedCost=num(e.target.value);day().sharedChecked=false;save();render()}catch(err){toast(err.message);e.target.value=day().sharedCost}};$('sharedChecked').onchange=e=>{day().sharedChecked=e.target.checked;save();stats()};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const ds=b.dataset;if(ds.close)$(ds.close).close();if(ds.editLead)leadModal(ds.editLead);if(ds.payLead)receiptModal(null,ds.payLead);if(ds.editReceipt)receiptModal(ds.editReceipt);if(ds.delLead){if(day().receipts.some(r=>r.leadId===ds.delLead))return toast('此名單已有款項，請先處理對應紀錄，避免丟失來源');if(confirm('確定刪除此名單？')){day().leads=day().leads.filter(l=>l.id!==ds.delLead);save();render()}}if(ds.delReceipt&&confirm('確定刪除此款項？請保留原始憑證。')){day().receipts=day().receipts.filter(r=>r.id!==ds.delReceipt);day().sharedChecked=false;save();render()}if(ds.copy){try{await navigator.clipboard.writeText($(ds.copy).textContent);toast('話術已複製')}catch{const r=document.createRange();r.selectNodeContents($(ds.copy));const s=getSelection();s.removeAllRanges();s.addRange(r);toast('已選取話術，請手動複製')}}});
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
$('exportBackup').onclick=()=>download('NOON100K-cold-v2-'+state.date+'.json',JSON.stringify(state,null,2),'application/json');$('importBackup').onclick=()=>$('backupFile').click();$('backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>4000000)throw Error('備份超過 4 MB');const s=validate(JSON.parse(await f.text()));if(!confirm('匯入會覆蓋這個瀏覽器的全部 V2 日期紀錄，不會合併。先匯出備份；確定繼續？'))return;state=s;canStore=true;save();render();toast('V2 備份已匯入；V1 資料沒有改動')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('exportCSV').onclick=()=>{const m=calc(),cell=v=>'"'+String(v??'').replace(/^[=+\-@]/,"'$&").replaceAll('"','""')+'"',rows=[['執行日','公司代稱','憑證代號','性質','填列實收','合格陌生實收','合格新收入','成本','淨貢獻','入帳時間','驗收時間','查核說明'],...m.rows.map(x=>[state.date,x.l?.name,x.r.ref,x.r.kind,x.r.cash,x.cash,x.gross,x.r.cost,x.net,x.r.paidAt,x.r.acceptedAt,x.reason]),[state.date,'共同成本','','','','',0,day().sharedCost,-day().sharedCost,'','',''],[state.date,'總計','','','',m.cash,m.gross,m.cost,m.net,'','',m.checked?'成本已核對':'成本未全核對']];download('NOON100K-cold-ledger-'+state.date+'.csv','\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8')};
$('printReport').onclick=()=>{document.querySelectorAll('.cold-phase').forEach(e=>e.open=true);window.print()};$('clearData').onclick=()=>{if(confirm('只清除目前執行日的 V2 代辦、名單及款項；V1 不變。確定已備份？')){state.days[state.date]=blankDay();save();render()}};
window.addEventListener('storage',e=>{if(e.key===KEY)toast('另一分頁已修改 V2；請勿同時編輯。先備份本頁再重新載入，避免互相覆蓋。')});
render();stats();setInterval(stats,1000);window.NoonCold={calc,validate,sourceReason,contactOK,signOK,blankDay,checkLead,checkReceipt,inWindow,time,TASKS,PHASES};
})();
