'use strict';
(()=>{
if(!window.NoonCold||!window.NoonProductV3)return;
const P=window.NoonProductV3.plans,KEY='noon100k-ops-v3',LEGACY='noon100k-cold-v2';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>'NT$ '+Math.round(n).toLocaleString('en-US'),owners={wei:'阿衛',wife:'太太',both:'共同'};
const DEFAULT={tax:5,hour:800,costs:{trial:[150,1.5,150],A:[4500,8,1000],B:[7500,12,1500],C:[20000,24,3000]}};
const tasks=[
['09:00–09:10','wei','09:00–09:04','用二十秒把商品說完整','練習「把服務說清楚，再接上需求表與追蹤表」。先定義商品，才問對方有沒有類似問題；本輪只選一種客群。','清楚說法與單一客群'],
['09:00–09:10','wife','09:00–09:04','核對收件窗口、供應與成本','手機開客戶頁、傳測試需求到現有 LINE 並確認管理端收到。向團隊核對固定成本、可接案數與開工日。','真人收件確認及供應依據'],
['09:00–09:10','both','09:04–09:07','共同看一次免費體驗與三種方案','理解 A 說清楚、B 接得住、C 交得順；B 為適配對象的主推，沒有需求就免費健檢或不接。','夫妻報價與說法一致'],
['09:00–09:10','both','09:07–09:10','通過出發檢查，不拿未確認承諾收錢','完成五項出發勾選；沒通過仍可做訪談，不送正式報價。09:00 前不建立本輪名單、不預約或預售。','出發條件／缺件記錄'],
['09:10–09:25','wei','09:10–09:20','人工查第一批陌生商家','從公開官網／商家頁找同一客群，確認營業與合理聯絡方式；寫一項可見現象，不預設一定有問題。','8–10 家查核目標，非成果保證'],
['09:10–09:25','wife','09:10–09:20','建立自己的少量陌生名單','與阿衛去重，不用親友、粉絲或轉介。每家留公開來源、查得時間、可談的服務情境。','3–5 家獨立名單與來源'],
['09:10–09:25','both','09:20–09:25','分配聯絡與示範版本','分配每家只由一人接觸；同一客群共用示範。先記錄版次 V3，不假裝八種行業全經過驗證。','分工及可複製的客戶連結'],
['09:25–09:55','wei','09:25–09:40','首輪陌生開場：先定義，再問需求','說明真實身分與公開來源，徵求一分鐘；用具體例子解釋商品，再問最近是否反覆補問價格、規格或時間。','實際接觸／決策者對話'],
['09:25–09:55','wife','09:25–09:40','平行首聯，不先免費做整站','同樣順序介紹商品。對方同意才傳服務頁與免費體驗；拒絕立即停止，不連環催訊。','同意看示範或拒絕原因'],
['09:25–09:55','wei','09:40–09:50','讓客戶用自己的話復述商品','問「照你看，我們會先幫你改善哪一段？」若還以為保證流量或全自動，就先澄清，不直接報價。','理解程度與共通誤解'],
['09:25–09:55','wife','09:40–09:50','用一個情境展示改造前後','只花約兩分鐘展示同行業範例，標明示範而非實績。詢問能否提供去識別的真實問題，不收敏感資料。','真實卡點與示範回饋'],
['09:25–09:55','both','09:50–09:55','記錄漏斗，不用稱讚冒充需求','分開記接通、理解、需求、意願與付款。詢問太少的商家先分流免費健檢，不硬推 B。','首輪觀察與下一步'],
['09:55–10:20','wei','09:55–10:05','第一場十分鐘健檢（有約才做）','問主服務、必要條件、最近一筆流程、每月詢問量、誰接手與誰決定。最多兩場真人免費健檢，其他約後續。','一個問題＋一個建議，不交整站'],
['09:55–10:20','wife','09:55–10:05','持續開發或完成另一場健檢','沒有約談就繼續首聯，不空填會議。依一樣問題表做判斷；本輪不要同時換行業、價格與話術。','可比較的訪談事實'],
['09:55–10:20','wei','10:05–10:15','依適配拿出三案比較','只缺說明用 A；說明＋詢問＋追蹤用 B；兩條流程多人交接用 C。信任不足先試作，無必要則不買。','推薦理由與不推薦理由'],
['09:55–10:20','wife','10:05–10:15','核對客戶需要付出的配合','確認能提供內容、圖片授權、收件帳號與指定窗口。資料還不齊只先試作，不承諾固定上線日。','資料清單及負責窗口'],
['09:55–10:20','both','10:15–10:20','決策點：有無能清楚描述價值的陌生人','不理解就改解釋；理解但沒痛點就改篩選；有需求卻不買，記預算、信任與時程，不立刻砍價。','本輪只改一個變項'],
['10:20–10:55','wei','10:20–10:35','產生一份範圍清楚的報價','先通過出發檢查及產能條件。選方案、列驗收、時程、首尾款與不含項目；正式承攬主體不能留白。','已經人工複核的書面報價'],
['10:20–10:55','wife','10:20–10:35','用單位工時貢獻把關，避免超接','填真實外包與工時估算，確認 B 是否仍是高效率方案。不是只看收多少，交付及獲客時間也要算。','成本、可開工日與承接量'],
['10:20–10:55','wei','10:35–10:45','處理疑問，讓客戶有比較依據','用問答庫說明差異：不是買 AI 帳號，不保證營收；目前工具已好用者不勉強換。真實回答不編假實績。','明確顧慮／補件內容'],
['10:20–10:55','wife','10:35–10:45','需要低風險時提出 2,980 試作','講清一頁對照、三題問答、六欄表草稿、一輪修改及兩工作天。不是免費製作，也不是明天必交完整版。','對試作範圍與費用的理解'],
['10:20–10:55','both','10:45–10:55','只記真實選擇與書面確認','在名單備註標 V3、所選方案及階段。試作轉建置沿用同公司，不新增一個假客戶；折抵不重複計收入。','版本、方案、付款與下一步'],
['10:55–11:35','wei','10:55–11:10','跟已約定回覆的人確認決定','沒有十萬元挑戰式施壓，不編造最後名額；不方便就約對方同意的後續時間。拒絕停止聯繫。','接受、拒絕或有日期的待決'],
['10:55–11:35','wife','10:55–11:10','核對真人實收與款項性質','自行查帳戶實收，不以開啟 LINE、需求單、付款截圖或口頭承諾當入帳。首款先列履約責任。','已查核憑證與對應名單'],
['10:55–11:35','wei','11:10–11:25','交接已成立案件，不急著虛構驗收','排客戶同意的資料準備、開工與驗收。只有實際在本輪完成且驗收的服務，才登已交付。','同意的履約安排'],
['10:55–11:35','wife','11:10–11:25','實際可完成才做第一份試作','先保護對外承諾；人力不夠就按約定工作天交付。完成、驗收與入帳三者須有事實，不為上午結算造假。','試作進度或真正驗收紀錄'],
['10:55–11:35','both','11:25–11:35','核對成本及重複收入','含陌生開發、健檢、試作、外包、工時、稅費及待付義務。試作折抵後，整案收款不可重複高於合約。','一份完整成本核對'],
['11:35–11:59','wei','11:35–11:45','結算陌生來源與商品理解證據','排除熟客與不明來源。分方案記理解、需求、報價、付款，不以免費體驗使用數宣稱產品市場契合。','有效樣本與分方案結果'],
['11:35–11:59','wife','11:35–11:45','分開結算訂單、現金與淨收益','嚴格保留原目標，不足十萬元就如實顯示；收到未來服務款，不等於已賺利潤。','收款／成本／履約責任'],
['11:35–11:59','both','11:45–11:59','備份並寫下一輪只改哪一件','匯出含 V2 名單及 V3 新代辦的完整備份。寫明哪句定位被理解、哪個方案被選、拒絕原因與交付事項。','完整備份及下一輪假設']
];
function blankDay(){return {ready:{},tasks:{},capacity:0,entity:'',cost:JSON.parse(JSON.stringify(DEFAULT))}}
let state={version:3,days:{}},canStore=true;try{const s=localStorage.getItem(KEY);if(s)state=validate(JSON.parse(s))}catch(e){canStore=false;console.warn('V3 storage not overwritten',e.message)}
function validate(s){if(s?.version!==3||!s.days||typeof s.days!=='object'||Array.isArray(s.days)||Object.keys(s.days).length>366)throw Error('V3 備份格式不符');const out={version:3,days:{}};for(const [d,v]of Object.entries(s.days)){if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!v)throw Error('日期格式錯誤');const n=blankDay();n.entity=String(v.entity||'').slice(0,120);n.capacity=Math.max(0,Math.min(100,Math.floor(Number(v.capacity)||0)));for(let i=0;i<5;i++)n.ready[i]=v.ready?.[i]===true;for(let i=0;i<tasks.length;i++)if(v.tasks?.[i])n.tasks[i]={done:v.tasks[i].done===true,note:String(v.tasks[i].note||'').slice(0,800)};for(const k of ['tax','hour'])if(Number.isFinite(v.cost?.[k])&&v.cost[k]>=0&&v.cost[k]<100000)n.cost[k]=v.cost[k];for(const k of Object.keys(P)){const a=v.cost?.costs?.[k];if(a&&Array.isArray(a)&&a.length===3&&a.every(x=>Number.isFinite(x)&&x>=0&&x<=10000000))n.cost.costs[k]=a.slice()}out.days[d]=n}return out}
function day(){const d=$('missionDate').value;return state.days[d]||(state.days[d]=blankDay())}
function save(){try{if(canStore)localStorage.setItem(KEY,JSON.stringify(state))}catch{canStore=false}if(!canStore)$('v3Storage').textContent='V3 無法自動儲存，關閉前先匯出完整備份。'}
const style=document.createElement('style');style.textContent='.v3-top{background:#e9f0da;border:1px solid #c7d5b5;border-radius:16px;padding:24px;margin:18px 0}.v3-top h2{margin:0 0 8px;font-size:25px}.v3-form{display:grid;grid-template-columns:1fr 1fr;gap:14px}.v3-form label{font-size:13px;display:block}.v3-form input,.v3-form select{width:100%;margin-top:6px}.v3-form .full{grid-column:1/-1}.v3-box{background:#f1f4eb;padding:16px;border-radius:10px;margin:12px 0}.v3-cost input{width:94px!important;min-width:70px;font-size:13px}.v3-cost .best{background:#eaf0d8}.v3-step{display:grid;grid-template-columns:24px 1fr;gap:11px;padding:17px 0;border-top:1px solid #e3e8db}.v3-step textarea{width:100%;min-height:45px;font-size:13px}.v3-step p{font-size:13px;margin:5px 0}.v3-step.done strong{text-decoration:line-through;color:#7c8875}.v3-check{display:flex!important;gap:10px;align-items:flex-start;margin:9px 0;line-height:1.8}.v3-check input{width:18px!important;margin-top:5px!important;flex-shrink:0}.v3-output{white-space:pre-wrap;font:14px/1.9 system-ui;word-break:break-word;background:#eef2e7;padding:20px;border-radius:12px}.v3-card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.v3-card-grid article{padding:16px;border:1px solid #d7dfcc;border-radius:10px}.v3-warn{color:#895119;font-size:13px}.v3-call{font-size:14px;line-height:1.9}.v3-hidden{display:none!important}@media(max-width:740px){.v3-form,.v3-card-grid{grid-template-columns:1fr}.v3-form .full{grid-column:auto}}';document.head.append(style);
const banner=document.createElement('section');banner.className='v3-top';banner.innerHTML=`<span class="cold-badge">V3｜先理解商品，再驗證陌生付款</span><h2>把服務說清楚，把每一次詢問接住。</h2><p>對外發「客戶服務頁」，不要把十萬元挑戰與內部成本表當銷售提案。</p><div class="cold-actions"><a class="btn btn-primary" id="clientLink" href="./service.html?src=cold-v3&v=3" target="_blank" rel="noopener noreferrer">開啟客戶服務頁 →</a><button class="btn btn-light" id="copyClient">複製客戶連結</button><a class="btn btn-light" href="#v3Ready">先做出發檢查</a></div><p class="cold-small">此頁仍是公開網址、未設登入保護。請勿分享內部操作台給客戶或填敏感資料；記錄僅存目前瀏覽器，不跨裝置同步。</p>`;$('overview').before(banner);
$('tasks').classList.add('v3-hidden');const taskRoot=document.createElement('section');taskRoot.id='tasksV3';taskRoot.className='cold-panel';taskRoot.innerHTML=`<div class="cold-row between"><h2>01 / V3 上午 30 項代辦</h2><strong id="v3Progress"></strong></div><p class="cold-small">V3 新代辦獨立計數，不沿用 V2 已完成勾選；原名單與收款仍保留。九點才查本輪名單。</p><div class="cold-row"><select id="v3Owner" aria-label="V3 負責人"><option value="all">全部</option><option value="wei">阿衛＋共同</option><option value="wife">太太＋共同</option><option value="both">共同</option></select><label><input type="checkbox" id="v3Unfinished"> 只看未完成</label><button class="btn btn-light btn-small" id="v3Expand">展開全部時段</button></div><div id="v3Tasks"></div>`;$('tasks').before(taskRoot);document.querySelectorAll('a[href="#tasks"]').forEach(a=>a.href='#tasksV3');
const ready=document.createElement('section');ready.id='v3Ready';ready.className='cold-panel';ready.innerHTML=`<h2>00 / 出發前先核對：能說、能收、能交付</h2><p>以下是需要你們實際完成的五項，不預設已完成。不通過仍可訪談與展示，但不產生對外正式報價。</p>${[
'已用手機操作客戶體驗與需求單，親自傳測試訊息至既有 LINE，並在管理端確認收到。',
'已核對正確承攬／收款主體、適用稅費、付款與取消條件；不是加盟總部提供的方案。',
'外包與夫妻工時已核對，可開工日、可接案數與第三方費用有依據；不是只有假設毛利。',
'客戶頁範圍、試作、修改、驗收與 AI 人工覆核限制已了解；未把示範當真實實績。',
'本輪 09:00 前名單與首聯為零；排除熟客、親友、舊案、既有粉絲與熟人介紹。'
].map((t,i)=>`<label class="v3-check"><input type="checkbox" data-v3ready="${i}"><span>${t}</span></label>`).join('')}<div class="v3-form"><label>正確承攬主體（發報價前必填）<input id="v3Entity" maxlength="120" placeholder="請填正式報價與收款的實際主體"></label><label>經查核仍可承接的案件數<input id="v3Capacity" type="number" min="0" max="100" step="1" value="0"></label></div><p class="v3-warn" id="v3Gate"></p><div class="cold-actions"><button class="btn btn-light" id="v3Selftest">檢查網頁內部功能</button><a class="btn btn-light" href="https://lin.ee/KaZ8bgl" target="_blank" rel="noopener noreferrer">開啟現有 LINE 測試</a></div><p class="cold-small" id="v3Test">自檢只檢查頁內模組；不能代替 LINE 收件、外包產能或銀行入帳的真人查核。</p>`;taskRoot.before(ready);
$('offer').innerHTML=`<h2>04 / 商品定位、比較、話術與正式報價</h2><div class="v3-box"><strong>一句話定義</strong><p>我們將商家的「賣什麼、適合誰、方案怎麼選」說清楚，再接上需求表、回覆範本與追蹤表。讓客戶知道怎麼問，員工知道下一步怎麼做。AI 只是人工操作的輔助工具。</p><p class="cold-small">可拓及需要諮詢、報價或預約的行業；明天仍只測一種客群。同一商品家族提供不同範圍，不把八種行業的成果混為同一已驗證模型。</p></div><div class="v3-card-grid">${['A','B','C'].map(k=>`<article><span class="cold-badge">${k}${k==='B'?'・預設主推（需適配）':''}</span><h3>${P[k].name}</h3><strong>${cash(P[k].price)}</strong><p class="cold-small">${P[k].scope.join('；')}</p></article>`).join('')}</div><p>引流：免費自助體驗 → 每家一次、約十分鐘真人健檢 → ${cash(P.trial.price)} 單點試作 → 合適才選建置。免費不等於整站客製；試作不等於已驗證正價建置的需求。</p><div class="cold-grid"><div><h3>先定義商品，再問能回答的問題</h3><div class="cold-pre" id="v3Script">你好，我是阿衛。我從你們公開商務頁面找到聯絡方式，方便用一分鐘說明一項服務嗎？不需要我就不打擾。

我們把商家的「賣什麼、方案差在哪、要先提供哪些資料」整理成清楚的服務頁，再接上需求表和追蹤表。不是買廣告，也不是賣 AI 帳號。

例如客人只問「多少錢」，我們先讓他看懂服務差別，再提供地點、規格、時間，讓你不用一直重問。你們最近有沒有類似情況？方便的話，我給你看一個兩分鐘的示範。

可以先免費體驗；只做一點試作是 2,980 元，完整建置依範圍為 19,800、39,800 或 69,800 元。不適合就不用買。</div><button class="cold-link" data-copy="v3Script">複製定位式開場</button></div><div><h3>客戶理解後，依序問六個問題</h3><div class="cold-pre">① 你最想讓客戶購買的主服務是什麼？
② 客戶比較方案時，最常誤解哪件事？
③ 最近一筆詢問，少了哪些資料才能報價？
④ 每月約有幾筆？補問大約花多久？
⑤ 誰接手、如何追蹤？現有工具夠用嗎？
⑥ 誰能決定？可接受投入與希望時間？

確認理解：「照你的理解，我們會替你改善哪一段？」
先對齊，不讓客戶不懂產品卻被要求提問。</div><h3>疑問回應選單</h3><select id="v3Objection" aria-label="客戶疑問">${['我還是不懂你們做什麼','我已經有網站／小編','太貴，為什麼值這個價','我怕付錢後做不出來','我沒有詢問，你能幫我找客嗎','我沒時間配合／我不懂 AI'].map((t,i)=>`<option value="${i}">${t}</option>`).join('')}</select><p class="v3-box" id="v3Answer"></p></div></div><details><summary>交付 SOP 與驗收關卡（點開逐項核對）</summary><p>1. 適配訪談：阿衛確認商品與問題，客戶提供服務與真實情境。<br>2. 範圍與報價：阿衛列價、範圍、窗口與排程，太太核對成本及產能，雙方書面確認後才收款。<br>3. 資料齊備：客戶提供合法圖片、價目、去識別樣本與最小必要授權，不傳密碼。<br>4. 文案及原型：太太定方向、外包製作，客戶先確認說法及欄位；一次整併意見。<br>5. 測試：手機／電腦、所有入口、表單收件、追蹤狀態、AI 人工覆核逐項測。<br>6. 驗收與交接：按所選方案驗收表完成，交帳號權責、可移交成果與教學，再依約收尾款。<br>7. 十四天錯誤修正：原範圍問題修正；新增範圍先報變更價，月維護另選。</p><p>範圍確認→文案確認→原型確認→正式驗收，每一步記確認人與日期。逾約定回覆時程先協調順延，不把沉默當驗收同意。</p></details><details><summary>試作升級記帳：同一家公司，不變出第二個客戶</summary><p>例：先收試作 2,980，後升 B，累計合約上限仍為 39,800。沿用原名單，把方案與總額改為 B，註記試作抵扣；後續兩期各 18,410。試作收入只在實際驗收後認列一次，不再把整筆 39,800 全部列為新增交付。收款憑證各自唯一，未來交付部分仍是預收。</p></details>
<h3 style="margin-top:24px">用真實成本確認主推方案</h3><p class="cold-small">下列是設計假設，不是廠商報價或實際淨利。計算會扣適用稅額估算、直接成本、夫妻工時和返工預備額；另有未分攤固定費。每小時貢獻越高不等於單案總貢獻最大。</p><div class="cold-row"><label class="cold-small">試算稅率 %（自行核對）<input type="number" id="v3Tax" min="0" max="50" step=".1"></label><label class="cold-small">夫妻工時每小時成本<input type="number" id="v3Hour" min="0" max="100000" step="1"></label></div><div class="scroll-x"><table class="cold-table v3-cost"><thead><tr><th>方案／參考總價</th><th>直接成本</th><th>夫妻工時</th><th>返工預備</th><th>預估貢獻</th><th>每小時貢獻</th></tr></thead><tbody id="v3CostRows"></tbody></table></div><p class="v3-box" id="v3Margin"></p>
<h3>產生範圍確認／報價文字</h3><p class="cold-small">只有出發條件全部核對、收款主體與產能已填，才能產生對外文字；仍需人工複核及客戶書面同意，按鈕不會自動寄出或收款。</p><form id="v3QuoteForm" class="v3-form"><label>客戶／商家代稱 *<input name="client" required maxlength="80"></label><label>所選方案<select name="plan">${Object.entries(P).map(([k,p])=>`<option value="${k}" ${k==='B'?'selected':''}>${p.name}／${p.price.toLocaleString()}</option>`).join('')}</select></label><label>待雙方確認的可開工日 *<input type="date" name="start" required></label><label>核心改善問題 *<input name="problem" required maxlength="200" placeholder="例如：服務範圍不明、詢問缺規格、報價後無追蹤"></label><label class="v3-check full"><input type="checkbox" name="credit"><span>同一商家已付試作 2,980 並完成驗收，本次升級在驗收後七日內；已核對折抵憑證。</span></label><label>試作驗收日（使用折抵時必填）<input type="date" name="accepted"></label><div class="full"><button type="submit" class="btn btn-primary" id="v3QuoteButton">核對完成後產生報價</button></div></form><p class="v3-warn" id="v3QuoteStatus" role="status"></p><div id="v3QuoteResult" hidden><pre class="v3-output" id="v3QuoteText"></pre><button class="cold-link" data-copy="v3QuoteText">複製報價，人工確認後再送出</button></div>`;
const backup=document.createElement('div');backup.className='v3-box';backup.innerHTML=`<h3>V3 一份完整備份</h3><div class="cold-actions"><button class="btn btn-primary" id="v3Export">匯出全部（含名單、收款、V3 代辦）</button><button class="btn btn-light" id="v3Import">還原完整備份</button></div><input id="v3File" type="file" accept="application/json,.json" hidden><p class="cold-small" id="v3Storage">V3 新代辦與成本另存，V2 名單及收款不刪除。不同裝置不即時同步；還原是覆蓋，不是合併。</p>`;$('backup').prepend(backup);
const stage=document.createElement('label');stage.className='full';stage.innerHTML=`V3 商品階段（將記入備註，金額仍須核對）<select id="v3LeadPlan"><option value="">未選／既有 V2 紀錄</option>${Object.entries(P).map(([k,p])=>`<option value="${k}">${p.name}</option>`).join('')}</select>`;$('leadForm').elements.amount.closest('label').after(stage);
$('v3LeadPlan').onchange=e=>{if(P[e.target.value])$('leadForm').elements.amount.value=P[e.target.value].price};new MutationObserver(()=>{if($('leadDialog').open){const m=$('leadForm').elements.next.value.match(/^\[V3\|([^|]+)\|/);$('v3LeadPlan').value=m&&P[m[1]]?m[1]:''}}).observe($('leadDialog'),{attributes:true,attributeFilter:['open']});
$('leadForm').addEventListener('submit',()=>{const k=$('v3LeadPlan').value;if(k){const f=$('leadForm').elements;f.next.value=`[V3|${k}|${P[k].name}] `+f.next.value.replace(/^\[V3\|[^\]]+\]\s*/,'')}},true);
function gate(){const d=day(),ok=[0,1,2,3,4].every(i=>d.ready[i])&&d.entity.trim()&&d.capacity>0;$('v3Gate').textContent=ok?'條件已由你們勾選確認；每案仍須複核排程、範圍與客戶同意。':'尚未通過全部出發條件。可以展示與訪談，暫不送正式報價或承諾收款。';$('v3QuoteButton').disabled=!ok;return !!ok}
function renderTasks(){const d=day(),who=$('v3Owner').value,hide=$('v3Unfinished').checked,open=new Set([...document.querySelectorAll('[data-v3phase][open]')].map(e=>e.dataset.v3phase));$('v3Progress').textContent=tasks.filter((_,i)=>d.tasks[i]?.done).length+' / '+tasks.length;const groups=[...new Set(tasks.map(t=>t[0]))];$('v3Tasks').innerHTML=groups.map((g,gi)=>{const rows=tasks.map((t,i)=>({t,i})).filter(({t,i})=>t[0]===g&&(who==='all'||t[1]===who||t[1]==='both')&&(!hide||!d.tasks[i]?.done));return rows.length?`<details data-v3phase="${gi}" ${open.has(String(gi))||(!open.size&&gi===0)?'open':''}><summary><strong>${g}</strong> · ${rows.length} 項</summary>${rows.map(({t,i})=>`<div class="v3-step ${d.tasks[i]?.done?'done':''}"><input type="checkbox" data-v3task="${i}" ${d.tasks[i]?.done?'checked':''} aria-label="${esc(t[3])}"><div><strong>${esc(t[3])}</strong><p>${esc(t[4])}</p><span class="cold-small">${t[2]} · ${owners[t[1]]} · 產出：${esc(t[5])}</span><details><summary class="cold-small">執行備註</summary><textarea data-v3note="${i}" maxlength="800" aria-label="${esc(t[3])}備註">${esc(d.tasks[i]?.note||'')}</textarea></details></div></div>`).join('')}</details>`:''}).join('')||'<p>此篩選目前沒有代辦。</p>'}
function margin(){const d=day(),rates=d.cost,rows=Object.entries(P).map(([k,p])=>{const [direct,h,reserve]=rates.costs[k],net=p.price/(1+rates.tax/100)-direct-h*rates.hour-reserve;return {k,p,direct,h,reserve,net,per:h?net/h:null}}),best=rows.filter(x=>x.per!==null).sort((a,b)=>b.per-a.per)[0];$('v3CostRows').innerHTML=rows.map(x=>`<tr class="${x===best?'best':''}"><td>${esc(x.p.name)}<small>${cash(x.p.price)}</small></td>${[x.direct,x.h,x.reserve].map((v,i)=>`<td><input type="number" min="0" max="${i===1?1000:10000000}" step="${i===1?.5:1}" value="${v}" data-v3cost="${x.k},${i}" aria-label="${x.p.name}${['直接成本','夫妻工時','返工預備'][i]}"></td>`).join('')}<td>${cash(x.net)}</td><td>${x.per===null?'無法計算':cash(x.per)}</td></tr>`).join('');$('v3Margin').textContent=best?.per>0?`目前假設下，${best.p.name}的每小時貢獻最高，約 ${cash(best.per)}；仍不是已賺淨利。B 預設以可重用模板限制工時，C 雖單價較高，額外交接與製作會吃掉效率。成本改變，主推判斷也要改；不能因此把不需要的方案賣給客戶。`:'目前假設沒有正的每小時貢獻，先調整範圍與成本，不為收款硬接。';}
function render(){const d=day();document.querySelectorAll('[data-v3ready]').forEach(e=>e.checked=d.ready[e.dataset.v3ready]===true);$('v3Entity').value=d.entity;$('v3Capacity').value=d.capacity;$('v3Tax').value=d.cost.tax;$('v3Hour').value=d.cost.hour;renderTasks();margin();gate();$('v3QuoteResult').hidden=true;$('v3QuoteForm').elements.start.min=$('missionDate').value;}
function invalidate(){save();$('v3QuoteResult').hidden=true;gate()}
document.addEventListener('change',e=>{const a=e.target;if(a.dataset.v3ready!==undefined){day().ready[a.dataset.v3ready]=a.checked;invalidate()}if(a.dataset.v3task!==undefined){const i=a.dataset.v3task;day().tasks[i]={...day().tasks[i],done:a.checked};save();renderTasks()}if(a.dataset.v3cost){if(!a.checkValidity()||a.value==='')return;const [k,i]=a.dataset.v3cost.split(',');day().cost.costs[k][i]=Number(a.value);day().ready[2]=false;document.querySelector('[data-v3ready="2"]').checked=false;invalidate();margin()}});
document.addEventListener('input',e=>{if(e.target.dataset.v3note!==undefined){const i=e.target.dataset.v3note;day().tasks[i]={...day().tasks[i],note:e.target.value};save()}});
$('v3Entity').oninput=e=>{day().entity=e.target.value;invalidate()};$('v3Capacity').onchange=e=>{if(e.target.checkValidity()){day().capacity=Number(e.target.value)||0;invalidate()}};for(const [id,k]of [['v3Tax','tax'],['v3Hour','hour']])$(id).onchange=e=>{if(!e.target.checkValidity()||e.target.value==='')return;day().cost[k]=Number(e.target.value);day().ready[2]=false;document.querySelector('[data-v3ready="2"]').checked=false;invalidate();margin()};$('missionDate').addEventListener('change',render);$('v3Owner').onchange=renderTasks;$('v3Unfinished').onchange=renderTasks;$('v3Expand').onclick=()=>{const es=[...document.querySelectorAll('[data-v3phase]')],v=es.some(e=>!e.open);es.forEach(e=>e.open=v);$('v3Expand').textContent=v?'收合全部時段':'展開全部時段'};
const answers=['我們把「客戶看懂商品」和「你收到完整需求」連起來。先用你的行業看一個例子，再決定是否有問題值得改善，不需要先懂 AI。','已經有工具不等於需要換。我們先看介紹、詢問與追蹤有沒有斷點；若已順暢就不建議重做，只補有價值的缺口。','費用對應到可驗收的範圍與交接，不以虛構營收保證價值。先用你的詢問量與工時算是否划算；預算或信任不足可以先單點試作，不直接砍價變成沒邊界。','先看公開示範，確認每項交付與驗收；需要時用 2,980 的小範圍試作驗證配合。沒有合適產能不先收建置款，也不拿假案例說服。','本案整理商品表達與詢問承接，不保證帶流量。完全沒詢問者先用免費體驗釐清商品與獲客渠道，不直接賣接單完整版。','你只需要提供真實服務資料並指定一位確認窗口；AI 模板有人帶操作。如果連資料與審稿都無法配合，先不要承諾建置時程。'];$('v3Objection').onchange=e=>$('v3Answer').textContent=answers[Number(e.target.value)];$('v3Answer').textContent=answers[0];
$('v3QuoteForm').addEventListener('input',()=>{$('v3QuoteResult').hidden=true});
function quote(f){if(!gate())throw Error('先完成五項出發核對、承攬主體與可接案數。');const k=f.plan.value,p=P[k],d=day(),start=f.start.value,mission=$('missionDate').value;if(!p||!start||start<mission)throw Error('請選有效方案及不早於本輪的可開工日。');let credit=0;if(f.credit.checked){if(k==='trial')throw Error('試作不能折抵自己。');const a=f.accepted.value,delta=(Date.parse(mission+'T00:00:00+08:00')-Date.parse(a+'T00:00:00+08:00'))/86400000;if(!a||!Number.isFinite(delta)||delta<0||delta>7)throw Error('請核對同商家試作驗收日，須在本輪報價日之前七日內。');credit=2980;}const remain=p.price-credit,first=k==='trial'?remain:remain/2;return `【商家接單流程改造｜V3 範圍與報價確認】\n報價日：${mission}\n承攬／收款主體：${d.entity.trim()}\n客戶代稱：${f.client.value.trim()}\n核心問題：${f.problem.value.trim()}\n\n方案：${k==='trial'?'單點試作':k+'｜'+p.name}\n參考總價（含適用稅費）：${cash(p.price)}\n已付試作折抵：${cash(credit)}${credit?'（須核對同商家付款、驗收與七日條件；含試作總計不超過方案總價）':''}\n本次餘額：${cash(remain)}\n${k==='trial'?'確認範圍與排程後一次支付：'+cash(first):'建置首款：'+cash(first)+'；約定驗收後尾款：'+cash(first)}\n\n交付範圍：\n${p.scope.map((s,i)=>(i+1)+'. '+s).join('\n')}\n\n可開工日：${start}，待雙方確認且客戶資料齊備、款項依約支付才起算。\n標準排程：約 ${p.days} 個工作天；等候客戶與第三方審核另協調，不默認順利通過。\n修改：${p.revisions} 輪範圍內整併意見；功能錯誤需修正，新增範圍先書面報變更價。\n驗收：${p.accept}\n\n客戶提供：正確服務資料、合法圖片、價目、去識別需求範例與指定窗口；用客戶自有帳號及最小必要授權，不傳密碼。\n不包含：廣告費、拍攝剪輯、代發、KOL／KOC、完整品牌重塑、客製 API／ERP、付費工具、網域／主機／平台與第三方授權。另列費用先經同意，不自動加購。\nAI 為人工操作模板，關鍵回覆、報價和承諾由真人確認，不保證曝光、成交或營業額。\n${k==='trial'?'試作不代上線；驗收後七日內升級，同商家已付試作費可折抵一次。':'上線後十四天範圍內錯誤修正，按約移交成果與帳號權責；6,800 元月維護另選，不自動續約。'}\n取消：按已執行且可說明工作及不可回復成本合理結算，未執行部分退回，細節寫進雙方契約，不排除適用的法定權利。\n\n請人工複核適用稅費、第三方費、日期與契約；本頁不自動成立訂單、不代寄、不收款。雙方書面確認後，再提供經核實的付款資料。`;}
$('v3QuoteForm').addEventListener('submit',e=>{e.preventDefault();try{$('v3QuoteText').textContent=quote(e.target.elements);$('v3QuoteResult').hidden=false;$('v3QuoteStatus').textContent='已產生文字，尚未送出。檢查範圍、承攬主體與日期後才傳給客戶。'}catch(err){$('v3QuoteStatus').textContent=err.message;$('v3QuoteResult').hidden=true}});
$('copyClient').onclick=async()=>{const u='https://larryveryhandsome.github.io/web-design/noon100k/service.html?src=cold-v3&v=3';try{await navigator.clipboard.writeText(u);$('copyClient').textContent='已複製客戶連結'}catch{prompt('請複製客戶連結',u)}};
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
$('v3Export').onclick=()=>{let v2=null;try{if(($('storageStatus').textContent||'').includes('無法')&&!window.NoonCold.snapshot)throw Error('名單儲存失敗');const raw=window.NoonCold.snapshot?JSON.stringify(window.NoonCold.snapshot()):localStorage.getItem(LEGACY);if(raw)v2=window.NoonCold.validate(JSON.parse(raw));else if(!canStore)throw Error('儲存不可用');else v2={schema:'noon100k-cold-v2',version:2,date:$('missionDate').value,days:{},updatedAt:0}}catch{alert('無法取得完整名單資料，已停止完整匯出。請先使用下方原名單備份，避免把不完整檔案當成完整備份。');return}download('NOON100K_V3_ALL_'+$('missionDate').value+'.json',JSON.stringify({schema:'NOON-V3-PACK',version:3,exportedAt:new Date().toISOString(),v2,ops:state},null,2))};$('v3Import').onclick=()=>$('v3File').click();$('v3File').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>6000000)throw Error('備份超過 6 MB');const p=JSON.parse(await f.text());if(p.schema!=='NOON-V3-PACK'||p.version!==3)throw Error('請選 V3 完整備份；V2 單獨備份請用下方原匯入功能。');const n=validate(p.ops),v=p.v2?window.NoonCold.validate(p.v2):null;if(!confirm('將覆蓋本瀏覽器 V3 操作資料'+(v?'與 V2 名單收款':'（此備份沒有 V2，原名單不動）')+'，不合併。已先備份並確認嗎？'))return;localStorage.setItem(KEY,JSON.stringify(n));if(v)localStorage.setItem(LEGACY,JSON.stringify(v));location.reload()}catch(err){alert('無法還原：'+err.message)}finally{e.target.value=''}};
$('v3Selftest').onclick=()=>{let stored=false;try{localStorage.setItem('noon-v3-test','1');stored=localStorage.getItem('noon-v3-test')==='1';localStorage.removeItem('noon-v3-test')}catch{}const checks=[['V3 商品設定',P.B.price===39800&&P.trial.price===2980],['30 項新代辦',tasks.length===30],['原陌生來源／收益模組',typeof window.NoonCold.calc==='function'],['報價與客戶入口',!!$('v3QuoteForm')&&!!$('clientLink')],['本機儲存',stored]];$('v3Test').textContent=checks.map(([n,v])=>(v?'✓ ':'✕ ')+n).join('｜')+'。這不代表 LINE 已收件、銀行已入帳或外包產能已確認。'};
$('printReport').addEventListener('click',()=>document.querySelectorAll('[data-v3phase]').forEach(e=>e.open=true),true);
window.addEventListener('storage',e=>{if([KEY,LEGACY].includes(e.key))$('v3Storage').textContent='另一分頁更動資料。請先備份，勿同時編輯；重新整理前核對，避免互相覆蓋。'});
render();window.NoonOpsV3={tasks,validate,quote,plans:P,defaultCosts:DEFAULT};
})();
