'use strict';
(()=>{
const P={
trial:{name:'單點試作',price:2980,days:2,revisions:1,training:15,scope:['30 分鐘訪談，限一項服務、一個卡點','一頁改善對照：三題問答＋最多六欄需求表草稿','一輪修正、15 分鐘交接；不代上線、不串帳號'],accept:'交付可編輯的一頁改善對照與需求表草稿；必填欄位與三題問答經客戶確認。'},
A:{name:'服務說清楚',price:19800,days:7,revisions:1,training:30,scope:['一項主力服務的定位、客群與方案表達','一頁式服務頁，最多六區塊','一份最多六欄的需求表＋五題回覆範本','一輪修改、30 分鐘教學'],accept:'手機與電腦服務頁能讀取；表單六欄內、一次測試可送達客戶指定的收件帳號；五題問答與連結正確。'},
B:{name:'詢問接得住',price:39800,days:10,revisions:2,training:60,scope:['A 的服務定位與一頁式頁面','需求表升為十欄＋十題回覆範本','一個 LINE 官方帳號的歡迎訊息與一組圖文選單','一份六狀態追蹤表＋兩套人工操作 AI 模板','三則導流文案、兩輪修改、60 分鐘教學'],accept:'A 的測試加上 LINE 選單與歡迎訊息檢查；需求能進追蹤表，負責人與下一步可更新；兩套 AI 模板以去識別樣本完成人工操作測試。'},
C:{name:'團隊交得順',price:69800,days:15,revisions:2,training:90,scope:['B 的內容，擴為兩項主服務／兩條詢問流程','最多兩頁服務頁、兩份各十欄內需求表','一個 LINE 官方帳號、二十題問答、四套 AI 模板','追蹤表分工規則，最多四位人員交接','三則導流文案、兩輪修改、90 分鐘教學＋一次 30 分鐘回顧'],accept:'兩條流程各完成一次端到端測試；四位以內人員的權責與接手規則清楚，四套 AI 模板可依操作說明使用。'}
};
const INDUSTRIES={
design:{label:'裝修／設計',service:'住宅裝修諮詢',problem:'只問「一坪多少」，卻不知道屋況、範圍與預算。',before:'想裝潢，請問多少錢？',fields:['所在地','室內坪數','屋況／屋齡','施作範圍','預算範圍','預計時程'],after:'先讓屋主知道設計、施工與局部改造的差別，再收必要條件，由設計師判斷是否適合約談。',metric:'需求完整率、反覆補問次數、合格約談數'},
home:{label:'清潔／家事',service:'居家清潔預約',problem:'清潔範圍與髒污程度不明，報價後才發現期待不同。',before:'幫我打掃一次多少錢？',fields:['服務區域','空間大小','清潔項目','現況照片（另傳）','希望日期','特殊需求'],after:'先區分日常、空屋、裝潢後清潔，再讓客戶填需求；不看現況就不保證最終價格。',metric:'報價補件次數、服務範圍爭議、確認預約數'},
wedding:{label:'婚禮／攝影',service:'婚禮畫師與攝影詢問',problem:'新人只看到作品，不清楚包含內容、檔期與加價項。',before:'婚禮畫畫可以報價嗎？',fields:['婚期','場地／區域','服務形式','服務時段','作品規格','預算範圍'],after:'作品旁就能比較現場與委託創作，再由真人確認檔期、交通和作品規格。',metric:'檔期合格詢問、規格補問次數、正式報價數'},
beauty:{label:'美容／美髮／寵物',service:'服務預約諮詢',problem:'項目很多，客戶選錯服務或漏說重要限制。',before:'想預約，有推薦的嗎？',fields:['想解決的需求','希望項目','目前狀況（非病歷）','日期時段','預算範圍','需真人確認事項'],after:'用非醫療性的服務分類協助客戶選項；健康或安全問題直接由具資格人員判斷。',metric:'選錯服務比例、預約資訊完整率、人工確認時間'},
travel:{label:'旅宿／體驗',service:'包棟住宿與體驗詢問',problem:'日期、人數、房型和使用限制反覆來回確認。',before:'包棟一晚多少？',fields:['入住／活動日期','人數','房型或體驗項目','預算範圍','交通需求','特殊條件'],after:'先說明可用方案與限制，再收詢問條件；本服務不取代房態系統，不保證有空房。',metric:'日期人數完整率、補問次數、確認訂單數'},
food:{label:'餐飲／團訂',service:'會議與活動餐盒',problem:'盒數、送達地點與餐別漏填，員工一直回頭確認。',before:'明天中午可以送便當嗎？',fields:['用餐日期／時間','送達區域','數量','每份預算','餐別／飲食限制','單據需求'],after:'先說清外送區域、最低量及提前天數，再收訂單條件；接單與食安由商家確認。',metric:'漏填訂單數、確認耗時、正確交付率'},
course:{label:'課程／教學',service:'課程與體驗諮詢',problem:'學員不知道程度差異，詢問後仍不知適合哪一班。',before:'你們課程怎麼收費？',fields:['想學的主題','目前程度','學習目標','可上課時段','上課形式','預算範圍'],after:'先比較課程程度、授課形式與適合對象，再由教師確認班別，不承諾學習成效。',metric:'程度匹配率、合格試課數、選課補問次數'},
b2b:{label:'製造／批發／設備',service:'企業詢價與維修需求',problem:'規格、數量和交期不全，業務無法正確估價。',before:'這個產品一批多少錢？',fields:['產品或服務','規格／用途','數量','交貨區域','希望交期','需提供的文件'],after:'把規格與採購條件一次收齊，再交業務判斷；技術認證、報價與交期不讓 AI 自行承諾。',metric:'有效規格完整率、首份報價耗時、錯誤報價數'}
};
const FAQ=[
['你們到底賣什麼？','一項有明確交付的「服務表達＋詢問承接」建置服務。從介紹內容、方案比較，到需求蒐集與人工追蹤，依方案交付可操作的頁面、表單與模板，不是只給建議的顧問報告。'],
['跟做網站、社群代操有何不同？','網站是其中一個接點。我們同時設計客戶看懂服務之後該填什麼、員工收到後如何處理。本案不含每天代發內容、拍攝剪輯、買廣告或 KOL／KOC 費用。已有網站可以先評估保留，不硬逼重做。'],
['我完全沒有客源，也適合嗎？','若主要問題是完全沒有曝光與詢問，建接單表本身不會變出客戶。先用免費體驗或小額試作確認商品表達，並另規劃你可負擔的獲客管道；不直接推薦完整建置。'],
['我已經有網站、LINE 和小編，為什麼還需要？','先看目前工具是否已連起來。如果客戶看得懂、資料完整、有人負責追蹤，其實未必需要我們。若介紹、詢問與內部處理之間仍斷開，就只補那個缺口。'],
['使用 AI 是不是會自動回客戶或自動成交？','不會。標準方案是員工主動使用 AI 模板整理去識別需求與草擬回覆，由真人確認。LINE 基本歡迎訊息與選單不等於即時 AI 客服；讀取聊天、客製 API、ERP 串接另案評估。'],
['能保證增加多少業績、幾個客人嗎？','不能。可驗收的是功能、範圍和操作；可觀察的是需求完整率、回覆時間與追蹤完成率。詢問量、價格、產品與業務能力都會影響成交，不能把示範當成已發生的成效。'],
['為什麼不自己請 AI 寫文案就好？','有能力自行整理、實作和驗收，自己做也合理。我們收費的是需求判斷、文案與視覺整合、工具建置、測試和人員交接，不是把提示詞當神奇秘方。'],
['免費體驗會不會最後才說要收錢？','本頁情境體驗免費，無須留電話。真人快速健檢每家一次、約 10 分鐘，需確認時段，只指出一個卡點與改善方向，不免費交付整站。不會自動續約或扣款。'],
['2,980 元試作到底會拿到什麼？','一項服務、一個卡點，30 分鐘訪談後交付可編輯的一頁改善對照：三題問答與六欄內需求表草稿。包含一輪修正與 15 分鐘交接，不含上線、帳號串接或完整品牌設計。'],
['試作升級如何折抵？','試作驗收後七個日曆日內，同一商家升級 A／B／C，可折抵已付的 2,980 元一次。未付不折、不與其他折扣重複。例：B 餘額 36,820 元，建置首款與尾款各 18,410 元；含試作合計仍為 39,800 元。'],
['付款方式與開工條件是什麼？','本頁不收款。先書面確認正確承攬主體、範圍、總價與可開工日；試作確認後一次支付，建置案原則 50% 首款、驗收後 50%。客戶資料齊備且雙方確認開工，才起算工作天。'],
['價格還會加哪些費用？','所示為標準範圍的試行參考總價，含適用稅費。網域、主機、LINE 訊息、付費 AI 工具、廣告、拍攝、圖庫與外掛授權不包含，開始前列出供應商與預估，需另經同意。不是一次付費永久包維運。'],
['我需要準備什麼？','服務與價目、可提供／不可提供的範圍、合法可用的圖片、常見問答、去識別詢問範例、指定窗口及收件帳號。資料不足先停在訪談或試作，不在空白資訊上編造商品承諾。'],
['交期是明天就全部完成嗎？','不是。試作約兩個工作天，A／B／C 標準排程約七／十／十五個工作天；均自資料齊備及雙方確認開工日起算。開工前須核對產能，第三方帳號審核和客戶回覆延誤要重新確認日期。'],
['修改幾次？不滿意怎麼處理？','試作／A 一輪，B／C 兩輪；一輪是由指定窗口整併一次範圍內意見。符合原需求但功能錯誤屬修正，不以修改輪次推託。新增服務、全新風格或範圍變動，先書面報變更價。'],
['上線後誰維護？網站和資料歸誰？','客戶以自己的帳號持有網站、表單與資料，依約提供可移交成果。上線後十四天內修正約定範圍的錯誤；第三方平台與授權仍受其條款限制。通用模板和既有工具不承諾獨家所有權。'],
['後續一定要月繳嗎？','不用。可自行操作。選購 6,800 元／月維護，含兩小時範圍內微調、一次 30 分鐘回顧，不含重做、代發、廣告和新串接。每月另確認，不自動續約；平台費另列。'],
['如何知道做了真的有用？','開工前先記既有基準；上線後比較相近期間的詢問量、必要欄位完整率、回覆耗時、追蹤完成率，並同時記廣告與促銷變動。樣本少或期間不同就標示限制，不只挑好看的數字。'],
['資料安全、取消與退款怎麼約定？','試作不收身分證、銀行資料、病歷或帳號密碼；正式案採客戶自有帳號與最小必要授權。取消依已執行且可說明的工作與不可回復成本合理結算，未執行部分退回，細節寫進契約，不排除適用的法定權利。'],
['你們適合所有行業嗎？','適用的是共同流程，不是每個產業都需要同樣服務。標準商品自助結帳且流程已順暢者，可能不需要；醫療、法律、金融等專業內容由具資格人員審核，標準方案不提供診斷、法律判斷或金融建議。']
];
window.NoonProductV3={plans:P,industries:INDUSTRIES,version:'3.0.0'};
const root=document.getElementById('serviceContent');if(!root)return;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>'NT$ '+Math.round(n).toLocaleString('en-US');
const planOptions=()=>'<option value="free">免費快速健檢（需約時段）</option>'+Object.entries(P).map(([k,p])=>`<option value="${k}">${p.name} · ${cash(p.price)}</option>`).join('');
root.innerHTML=`
<section class="block" id="definition"><div class="section-top"><div class="eyebrow">01 / 先知道我們解決哪一件事</div><h2>不是讓你多一套工具。<br>是把三個斷點接起來。</h2><p class="lead">先說明商品，客戶才知道怎麼問；先定義問題，員工才知道怎麼答。</p></div><div class="grid"><article class="card"><div class="num">表達的斷點</div><h3>有服務，卻讓人看不懂</h3><p>只列「專業、優質、歡迎私訊」，客戶無法分辨適不適合。</p><strong>交付：服務定位、適合對象、方案比較與常見問題。</strong><p class="small">觀察客戶能否說出差別，不把「看懂」直接等同成交。</p></article><article class="card"><div class="num">詢問的斷點</div><h3>有詢問，卻一直來回補問</h3><p>價格、地點、範圍、時間分散在聊天，報價前得重問一次。</p><strong>交付：必要欄位、詢問入口、回覆與 AI 整理範本。</strong><p class="small">觀察資料完整率與處理時間，重要內容真人確認。</p></article><article class="card"><div class="num">交接的斷點</div><h3>有報價，卻沒有下一步</h3><p>不知道誰負責，也忘記何時答覆，不是再多發幾篇文就能解決。</p><strong>交付：狀態、負責人、約定回覆時間與操作教學。</strong><p class="small">觀察追蹤完成率，不連環催單，也不自動代客決定。</p></article></div><div class="banner"><strong>適合：</strong>有真實服務、需要諮詢／報價／預約，且願意指派一位窗口的商家。<br><strong>先別買完整版：</strong>完全沒客源、商品還沒定義、工具已夠用，或期待保證業績與無人全自動的人。</div></section>
<section class="block" id="situations"><div class="section-top"><div class="eyebrow">02 / 不限行業，先看你是哪種詢問</div><h2>換一個行業，<br>你就知道能怎麼用。</h2><p>以下全是情境示範，不是既有客戶案例或成效證明。同一套底層流程，依業務更換欄位、語氣與人工把關點。</p></div><div class="tabs" role="tablist" aria-label="行業情境">${Object.entries(INDUSTRIES).map(([k,v])=>`<button class="tab" id="tab-${k}" role="tab" data-sector="${k}" aria-controls="industryExample" aria-selected="${k==='design'}">${v.label}</button>`).join('')}</div><div id="industryExample" role="tabpanel" aria-labelledby="tab-design" tabindex="0"></div></section>
<section class="block" id="experience"><div class="section-top"><div class="eyebrow">03 / 先體驗，不用先留電話</div><h2>用三個問題，<br>找到你該先改善的地方。</h2><p>這是瀏覽器內的規則式體驗，不是即時 AI 診斷。你的輸入不會自動傳給我們。</p></div><div class="grid two"><form class="card" id="experienceForm"><div class="form-grid"><label class="full">你的產業<select id="exSector">${Object.entries(INDUSTRIES).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select></label><label class="full">目前最困擾的事<select id="exPain"><option value="explain">客戶不清楚我賣什麼、差別在哪</option><option value="intake">詢問一直補資料，反覆回答</option><option value="follow">報價後沒人追蹤，員工交接散亂</option><option value="traffic">根本沒有曝光或詢問</option><option value="fine">現有流程順暢，只是想了解</option></select></label><label>每月約有幾筆詢問？<input id="exVolume" type="number" min="0" max="100000" step="1" value="20" required></label><label>需要幾條接單流程？<select id="exFlows"><option value="1">一項主服務／一條</option><option value="2">兩項服務／兩條</option><option value="3">更多或需串接系統</option></select></label></div><button class="button" type="submit" style="margin-top:20px">產生我的改善示範 →</button><p class="small" style="margin-top:12px">每月筆數僅作對話起點，不是投資效益的門檻。</p></form><div class="card"><div class="badge">免費・不綁訂閱</div><h3 style="margin-top:18px">先看差別，再決定值不值得。</h3><div id="experienceResult" aria-live="polite"><p>選擇情境後，你會看到：建議先改哪一件、需要問客戶哪些資料，以及為什麼不一定要買最大的方案。</p></div></div></div><div class="grid two" style="margin-top:22px"><article class="card"><div class="badge">第一步 / 免費真人快速健檢</div><h3 style="margin-top:14px">10 分鐘，確認一個卡點。</h3><p>你提供公開服務頁或去識別化說明，我們用一次短談指出一個流程問題與下一步。不含整站設計、客製文件或直接開工。</p><p class="small">每家一次，需先確認可回覆時段；網頁體驗不限次數。需求不適合，就直接說明。</p><button class="button light" data-plan="free">先申請免費健檢</button></article><article class="card"><div class="badge">第二步 / 可驗收的小額試作</div><h3 style="margin-top:14px">${cash(P.trial.price)}，只做一個小改善。</h3><p>${P.trial.scope.join('；')}。</p><p class="small">資料齊備並確認開工後約兩個工作天。驗收後七日內升級建置，已付試作費可折抵一次；不升級也保留試作成果。</p><button class="button" data-plan="trial">詢問單點試作</button></article></div></section>
<section class="block" id="plans"><div class="section-top"><div class="eyebrow">04 / 只買你目前用得上的範圍</div><h2>三種建置深度。<br>不是三種模糊的承諾。</h2><p>標準範圍試行參考總價，含適用稅費、單次建置、不自動續約。先確認需求、產能與書面報價，本頁不收款。</p></div><div class="grid">${['A','B','C'].map(k=>{const p=P[k];return `<article class="card plan ${k==='B'?'recommended':''}">${k==='B'?'<div class="recommend-label">建議：需要說明＋詢問＋追蹤的商家</div>':''}<div class="eyebrow">PLAN ${k}</div><h3>${p.name}</h3><div class="price">$${p.price.toLocaleString('en-US')}<small> / 次</small></div><p>${k==='A'?'先讓客戶理解一項主力服務。':k==='B'?'把看懂、詢問到人工追蹤接起來。':'兩條流程，需要多人分工與交接。'}</p><ul>${p.scope.map(s=>`<li>${s}</li>`).join('')}</ul><p class="small">約 ${p.days} 個工作天＊｜${p.revisions} 輪修改<br>首款 ${cash(p.price/2)}；驗收尾款同額</p><button class="button ${k==='B'?'':'light'}" data-plan="${k}">了解 ${k} 方案</button></article>`}).join('')}</div><div class="banner"><strong>＊起算條件：</strong>客戶資料齊備＋首款依約支付＋雙方確認開工日。不是付款後不論資料與審核狀況都保證同一天交付。<br><strong>不包含：</strong>廣告投放與費用、拍攝剪輯、完整品牌重塑、KOL／KOC、客製 API／ERP、付費工具與無限修改。LINE 仍是一個官方帳號；AI 是人工操作模板。</div><div class="scroll"><table><caption style="text-align:left;font-weight:700;padding:10px">方案差別再核對一次（升級數量為總數，不重複相加）</caption><thead><tr><th>比較項目</th><th>A 說清楚</th><th>B 接得住</th><th>C 交得順</th></tr></thead><tbody><tr><td>主服務／頁面／需求表</td><td>1／1／1（6 欄）</td><td>1／1／1（10 欄）</td><td>2／2／2（各 10 欄）</td></tr><tr><td>問答範本／AI 模板</td><td>5 題／不含</td><td>10 題／2 套</td><td>20 題／4 套</td></tr><tr><td>LINE 基本設定</td><td>既有聯絡入口</td><td>歡迎訊息＋一組圖文選單</td><td>同 B，一個帳號</td></tr><tr><td>內部追蹤</td><td>表單收件</td><td>六狀態追蹤表</td><td>追蹤表＋最多四人的分工規則</td></tr><tr><td>導流文案</td><td>不含</td><td>3 則文字，非代發</td><td>3 則文字，非代發</td></tr><tr><td>教學／修改／回顧</td><td>30 分／1 輪／不含</td><td>60 分／2 輪／不含</td><td>90 分／2 輪／1 次 30 分鐘</td></tr></tbody></table></div><details><summary>完成後可自行操作；需要協助才選 6,800 元／月維護</summary><p>每月兩小時範圍內微調＋一次 30 分鐘回顧；不含全新頁面、拍攝、代發、廣告和新串接。每月另確認，不自動續約。平台與授權費另列，超時先報價。三種建置均含上線後十四天的範圍內錯誤修正，並非承諾平台永不出錯。</p></details></section>
<section class="block" id="value"><div class="section-top"><div class="eyebrow">05 / 用你自己的數字判斷</div><h2>效益要能說明，<br>也要能被核對。</h2><p>以下預填數值是可修改的假設，不是任何客戶的真實成果。節省時間是機會成本，不必然減少現金支出；不預測成交率。</p></div><div class="grid two"><form id="valueForm" class="card"><div class="form-grid"><label>每月詢問筆數<input id="valCount" type="number" min="0" max="100000" value="80" step="1"></label><label>每筆原耗時（分鐘）<input id="valBefore" type="number" min="0" max="1440" value="10" step="1"></label><label>改善後假設耗時（分鐘）<input id="valAfter" type="number" min="0" max="1440" value="5" step="1"></label><label>每小時時間價值（元）<input id="valHour" type="number" min="0" max="100000" value="350" step="1"></label><label>一筆新交易的貢獻（元）<input id="valProfit" type="number" min="0" max="10000000" value="4000" step="1"><small>售價扣該筆變動成本，非總營收</small></label><label>評估方案<select id="valPlan">${['A','B','C'].map(k=>`<option value="${k}" ${k==='B'?'selected':''}>${k}／${P[k].price.toLocaleString()}</option>`).join('')}</select></label></div></form><div class="card" id="valueResult" aria-live="polite"></div></div><div class="banner">開工前與上線後使用相近期間，核對「必要欄位完整率、每筆回覆時間、追蹤完成率」。若樣本太少，或廣告、季節、售價同時改變，就不把差異全歸功於本服務。</div></section>
<section class="block" id="process"><div class="section-top"><div class="eyebrow">06 / 不只寫「交給我們」</div><h2>你做什麼、我們做什麼，<br>每一步都有交付。</h2></div><div class="steps">${[
['體驗與適配確認','你：選情境，說明一項服務與一個困擾。','我們：確認是否適合；無詢問或需求不明者，先免費體驗／試作。輸出：適配判斷，非成交承諾。'],
['書面範圍與排程','你：選方案、指定一位確認窗口，確認預算。','我們：列總價、首尾款、第三方費、承攬主體、修改及取消條件。確認產能後才收款。輸出：雙方確認的範圍表。'],
['資料與基準盤點','你：提供服務價目、範圍、合法圖片、去識別範例、客戶自有帳號授權。','我們：記現況指標，畫服務→詢問→真人處理流程。資料不足先標記，不編造。輸出：定位與流程初稿。'],
['原型確認與製作','你：先確認說法與欄位，再由同一窗口整合修改。','我們：製作所選範圍的頁面／表單／模板；基本 LINE 與追蹤只在相應方案實施。輸出：可測試原型與修改紀錄。'],
['端到端測試與驗收','你：用一筆測試需求操作，核對收到的資料與後續處理。','我們：測手機／電腦、必填與錯誤提示、聯絡與收件、分工、AI 人工覆核。輸出：測試紀錄與待修清單；有問題先修，不拿營收取代驗收。'],
['移交、尾款與後續','你：完成約定驗收及尾款，指定日常管理者。','我們：交付成果、帳號與操作教學；十四天範圍內錯誤修正。輸出：移交清單；月維護另選、不強制。']].map(s=>`<article class="step"><div><strong>${s[0]}</strong><p>${s[1]}</p></div><div><p>${s[2]}</p></div></article>`).join('')}</div><details><summary>各方案的驗收標準</summary>${Object.entries(P).map(([k,p])=>`<p><strong>${k==='trial'?'試作':k}｜${p.name}：</strong>${p.accept}</p>`).join('')}</details></section>
<section class="block" id="faq"><div class="section-top"><div class="eyebrow">07 / 你可能想問的，我們先說清楚</div><h2>不懂 AI，也能把問題問完整。</h2></div>${FAQ.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>
<section class="block" id="inquiry"><div class="section-top"><div class="eyebrow">08 / 先把需求整理好，再開啟對話</div><h2>不用想專業名詞。<br>照這幾題填就好。</h2><p>先在此產生需求單，再複製到 LINE 並由你按送出。這不是自動送件或預約成功通知。</p></div><form class="card" id="briefForm"><div class="form-grid"><label>商家／工作室代稱<input name="business" maxlength="80" placeholder="可先不填真實公司名稱"></label><label>你的行業<select name="industry">${Object.entries(INDUSTRIES).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select></label><label class="full">你最希望客戶買的那一項服務 *<input name="service" required maxlength="200" placeholder="例如：空屋清潔、老屋裝修、企業餐盒"></label><label class="full">你希望先解決什麼？ *<textarea name="problem" required maxlength="1000" placeholder="例如：一直被問多少錢，但對方沒有提供坪數和範圍"></textarea></label><label>想先了解的方案<select name="plan" id="briefPlan">${planOptions()}</select></label><label>希望何時開始<input name="when" maxlength="100" placeholder="例如：下個月；尚未確定也可以"></label><label class="full checkline"><input type="checkbox" required><span>我知道這份資料只在目前頁面產生，還要自行傳送；不填個人身分證、密碼、病歷或未經同意的客戶資料。</span></label></div><button type="submit" class="button" style="margin-top:18px">產生需求單，不自動傳送</button></form><div class="result" id="briefResult" hidden><strong>需求單已產生，尚未傳送。</strong><pre class="output" id="briefText"></pre><div class="actions"><button class="button" id="copyBrief">① 複製需求單</button><a class="button light" href="https://lin.ee/KaZ8bgl" target="_blank" rel="noopener noreferrer">② 開啟服務 LINE</a><button class="button light" id="downloadBrief">下載文字備份</button></div><p class="small">③ 在 LINE 貼上並按「送出」，待真人確認收到、適配與時段。電腦可能顯示 QR Code，可用手機開啟。開啟 LINE 或複製文字，都不代表我們已收到。</p></div></section>
<section class="block" id="privacy"><div class="cta"><h2>先理解服務，<br>再決定要不要合作。</h2><p>不用買最大的。也不用為了 AI 而用 AI。先挑一個真實問題，確認改善方向，再投入預算。</p><a class="button lime" href="#experience">回到免費情境體驗 →</a><p class="small" style="margin-top:18px">資料原則：本頁不自動儲存表單輸入或傳送至伺服器，重新整理會清除；不放追蹤像素。自行透過 LINE 送出的資訊由接收窗口與該平台處理。正式專案另約資料授權、保密、保存與刪除方式。</p></div></section>`;
let currentSector='design',lastBrief='';
function sector(k){if(!INDUSTRIES[k])k='design';currentSector=k;const d=INDUSTRIES[k];document.querySelectorAll('[data-sector]').forEach(e=>e.setAttribute('aria-selected',String(e.dataset.sector===k)));$('industryExample').setAttribute('aria-labelledby','tab-'+k);$('industryExample').innerHTML=`<div class="grid two"><div class="card before"><span class="label">改造前 / ${d.label}</span><h3>「${d.before}」</h3><p>${d.problem}</p></div><div class="card after"><span class="label">改造後 / ${d.service}</span><p>${d.after}</p><div class="sample-fields">${d.fields.map(f=>`<span>${f}</span>`).join('')}</div><p class="small" style="margin-top:16px">可以觀察：${d.metric}。不把它當成保證改善。</p></div></div>`;$('exSector').value=k;}
function choose(k){$('briefPlan').value=P[k]?k:'free';$('inquiry').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('briefResult').hidden=true;lastBrief='';}
function showToast(t){$('serviceToast').textContent=t;$('serviceToast').hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('serviceToast').hidden=true,5500)}
async function copy(text){try{await navigator.clipboard.writeText(text);showToast('已複製，請到 LINE 貼上並親自送出。')}catch{const el=$('briefText'),r=document.createRange();r.selectNodeContents(el);const s=getSelection();s.removeAllRanges();s.addRange(r);showToast('瀏覽器未允許複製，已選取文字，請手動複製。')}}
function recommend(pain,volume,flows){if(pain==='fine')return {plan:'free',why:'你描述的流程已順暢，先不用買。可以用免費健檢確認是否真的有缺口。'};if(pain==='traffic'||volume===0)return {plan:'free',why:'你目前主要缺詢問；這套流程不會自動帶來流量。先釐清服務與獲客方式，不推薦直接建完整版。'};if(flows>2)return {plan:'trial',why:'需求超出標準兩條流程，先用單點試作釐清範圍，再個別評估，不直接承諾串接。'};if(flows===2)return {plan:'C',why:'兩項主服務需要各自的欄位與交接，C 才包含兩條流程；也可以先用試作驗證其中一條。'};if(pain==='explain')return {plan:'A',why:'目前重點是服務說明，A 已涵蓋定位、一頁服務頁與基本需求表，不需要先買完整追蹤。'};return {plan:'B',why:'你描述的是需求補問或後續追蹤，B 才包含 LINE 基本接待、追蹤表與人工 AI 模板。是否值得仍需看實際詢問量、成本及人員配合。'};}
$('experienceForm').addEventListener('submit',e=>{e.preventDefault();const k=$('exSector').value,d=INDUSTRIES[k],n=Number($('exVolume').value),r=recommend($('exPain').value,n,Number($('exFlows').value));$('experienceResult').innerHTML=`<span class="badge">${d.label}・規則式初步建議</span><h3 style="margin-top:15px">${r.plan==='free'?'先免費確認需求':P[r.plan].name}</h3><p>${r.why}</p><p><strong style="font-size:16px">可以先這樣告訴你的客戶：</strong>「我們提供${d.service}，先確認${d.fields.slice(0,3).join('、')}，再由真人評估合適方案與報價。」</p><div class="sample-fields">${d.fields.map(f=>`<span>${f}</span>`).join('')}</div><p class="small" style="margin-top:12px">欄位是示範，還要按你的實際服務修正。沒有自動回客、預約或報價。</p><button class="button sm" data-plan="${r.plan}">把這個方向帶去詢問</button>`;sector(k);$('briefForm').elements.industry.value=k;});
function value(){const ids=['valCount','valBefore','valAfter','valHour','valProfit'];if(ids.some(id=>!$(id).checkValidity()||$(id).value==='')){$('valueResult').innerHTML='<p>請填入有效的非負數值。</p>';return}const [n,b,a,h,u]=ids.map(id=>Number($(id).value)),t=n*(b-a)/60,p=P[$('valPlan').value];$('valueResult').innerHTML=`<span class="badge">假設試算，不是成果報告</span><h3 style="margin-top:17px">每月處理時間可能${t>=0?'減少':'增加'}</h3><strong class="big">${Math.abs(t).toFixed(1)} 小時</strong><p>計算：${n} 筆 ×（${b} − ${a}）分鐘 ÷ 60。</p><p>按每小時 ${cash(h)} 估計，時間機會價值約 ${cash(Math.abs(t)*h)}。${t<0?'此情境反而增加負擔，需重新設計。':'不是保證節省的現金，也不表示可裁減人力。'}</p><p>單靠新增交易貢獻覆蓋 ${cash(p.price)} 建置費：${u>0?`需要約 <strong>${Math.ceil(p.price/u)} 筆</strong>、每筆貢獻 ${cash(u)} 的額外交易。`:'尚未填正的單筆貢獻，無法計算。'}</p><p class="small">沒有預測能多接幾筆或多久回本，未納入持續工具費與維護。若對你不划算，先自助或試作。</p>`;}
$('valueForm').addEventListener('input',value);$('valueForm').addEventListener('submit',e=>e.preventDefault());
$('briefForm').addEventListener('submit',e=>{e.preventDefault();const f=e.target.elements,p=f.plan.value,name=P[p]?.name||'免費快速健檢',price=P[p]?cash(P[p].price):'免費，需先確認時段';lastBrief=`【商家接單流程改造・V3 需求單】\n商家代稱：${f.business.value.trim()||'待補'}\n行業：${INDUSTRIES[f.industry.value].label}\n主力服務：${f.service.value.trim()}\n想改善：${f.problem.value.trim()}\n想了解：${name}（${price}）\n希望開始：${f.when.value.trim()||'待討論'}\n來源：${new URLSearchParams(location.search).get('src')==='cold-v3'?'陌生開發 V3 服務頁':'V3 公開服務頁'}\n\n請先確認需求是否合適、可回覆時段、範圍與正式報價；這份需求單不是訂單或付款承諾。`;$('briefText').textContent=lastBrief;$('briefResult').hidden=false;});
$('briefForm').addEventListener('input',()=>{lastBrief='';$('briefResult').hidden=true});$('copyBrief').onclick=()=>lastBrief&&copy(lastBrief);$('downloadBrief').onclick=()=>{if(!lastBrief)return;const u=URL.createObjectURL(new Blob([lastBrief],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='商家接單流程_V3_需求單.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)};
document.addEventListener('click',e=>{const t=e.target.closest('[data-sector],[data-plan]');if(!t)return;if(t.dataset.sector)sector(t.dataset.sector);if(t.dataset.plan)choose(t.dataset.plan)});
document.querySelector('[role=tablist]').addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-sector]')],i=tabs.indexOf(document.activeElement);if(i<0||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();sector(tabs[next].dataset.sector)});
const params=new URLSearchParams(location.search);sector(params.get('sector')||'design');if(P[params.get('plan')])$('briefPlan').value=params.get('plan');value();window.NoonProductV3.recommend=recommend;
})();
